name: shortcut-app
version: '0.4.0'
summary: Make app shortcuts
description: |
      Shortcut is a tool that allows users to quickly pin executable files to their app launcher.
      It guides users throught the process by providing file pickers with relevant filters, input validation, and name and icon previews.

base: core22
grade: stable #devel
confinement: strict #devmode
architectures:
  - amd64
  - arm64
  - armhf

slots:
  shortcut:
    interface: dbus
    bus: session
    name: io.github.andreibachim.shortcut

plugs:
  target-dir:
    interface: personal-files
    write:
      - $HOME/.local/share/applications
  home:
    interface: home

parts:
  shortcut:
    build-packages: [cargo, rustc]
    plugin: rust
    source: .
    override-pull: |
      craftctl default
      rustup update

apps:
  shortcut:
    extensions: [gnome]
    command: bin/shortcut 
