name: shortcut
version: '0.4.0'
summary: Make app shortcuts
description: |
      Shortcut is a tool that allows users to quickly pin executable files to their app launcher.
      It guides users throught the process by providing file pickers with relevant filters, input validation, and name and icon previews.

base: core22
grade: stable #devel
confinement: strict #devmode

slots:
  shortcut:
    interface: dbus
    bus: session
    name: io.github.andreibachim.shortcut

apps:
  shortcut:
    extensions: [gnome]
    command: target/release/shortcut

plugs:
  target-dir:
    interface: personal-files
    write:
      - $HOME/.local/share/applications
  home:
    interface: home

parts:
  shortcut:
    plugin: dump
    source: .
    source-type: local
    organize: 
      data/io.github.andreibachim.shortcut.gschema.xml: /usr/share/glib-2.0/schemas/io.github.andreibachim.shortcut.gschema.xml
    override-prime: |
      craftctl default
      glib-compile-schemas /usr/share/glib-2.0/schemas/

