name: shortcut
base: core22
version: '0.3.1'
summary: Make app shortcuts
description: |
  Simple application to create shortcuts for apps using only a name, an icon and an executable path.

grade: stable #devel
confinement: strict #devmode

slots:
  shortcut:
    interface: dbus
    bus: session
    name: io.github.andreibachim.shortcut

plugs:
  target-dir:
    interface: personal-files
    write:
      - $HOME/.local/share/applications

apps:
  shortcut:
    extensions: [gnome]
    command: target/release/shortcut
    plugs:
      - target-dir
      - home

parts:
  shortcut-part:
    plugin: dump
    source: .
    source-type: local
    organize: 
      data/io.github.andreibachim.shortcut.gschema.xml: /usr/share/glib-2.0/schemas/io.github.andreibachim.shortcut.gschema.xml
    override-prime: |
      craftctl default
      glib-compile-schemas /usr/share/glib-2.0/schemas/

