name: shortcut
version: '0.3.1'
summary: Make app shortcuts
description: |
  Pin app shortcuts to your launcher using only a name, icon and executable path.

base: core22
grade: stable #devel
confinement: strict #devmode

slots:
  shortcut:
    interface: dbus
    bus: session
    name: io.github.andreibachim.shortcut

apps:
  shortcut:
    extensions: [gnome]
    command: target/release/shortcut

plugs:
  target-dir:
    interface: personal-files
    write:
      - $HOME/.local/share/applications
  home:
    interface: home

parts:
  shortcut:
    plugin: dump
    parse-info: [data/io.github.andreibachim.shortcut.metainfo.xml]
    source: .
    source-type: local
    organize: 
      data/io.github.andreibachim.shortcut.gschema.xml: /usr/share/glib-2.0/schemas/io.github.andreibachim.shortcut.gschema.xml
    override-prime: |
      craftctl default
      glib-compile-schemas /usr/share/glib-2.0/schemas/

