name: shortcut-app
version: '0.4.0'
summary: Make app shortcuts
description: |
      Shortcut is a tool that allows users to quickly pin executable files to their app launcher.
      It guides users throught the process by providing file pickers with relevant filters, input validation, and name and icon previews.

base: core22
grade: stable #devel
confinement: strict #devmode
architectures: [amd64, arm64, armhf]

plugs:
  target-dir:
    interface: personal-files
    write:
      - $HOME/.local/share/applications
  home:
    interface: home

parts:
  rust-deps:
    plugin: nil
    build-packages:
      - curl
    override-pull: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  shortcut-app:
    after: [rust-deps]
    build-packages: [cargo, rustc]
    plugin: rust
    source: .
  compile-schemas:
    after: [shortcut-app]
    plugin: dump
    source: .
    organize:
      data/io.github.andreibachim.shortcut.gschema.xml: usr/share/glib-2.0/schemas/io.github.andreibachim.shortcut.gschema.xml
    override-prime: |
      craftctl default
      glib-compile-schemas usr/share/glib-2.0/schemas

apps:
  shortcut-app:
    extensions: [gnome]
    command: bin/shortcut 
